### ISSUE TITLE
Bad programing class character creation not case insensitive

### ISSUE THREAD

**Issue by CallumWigg** [OwenFeik/spells#2]
didnt recognise "Druid" only "druid"
honeslty, excpeted better programming from someone posting stuff, the nerve honestly
it did however be case insensitivew when the character had beebn made, so me thinks thats him just beiong really bad,  you could say he was insentisitve to me

fix it or im suuing

\kind regards
callum : )

**Comment by OwenFeik** [comment]
Fixed in [this commit](https://github.com/OwenFeik/spells/commit/094105c262b3488d08ee55fd1cb5832c0a285626). Thank you for your feedback, no lawsuit should be necessary.
