### ISSUE TITLE
Exit command fails

### ISSUE THREAD

**Issue by CallumWigg** [OwenFeik/spells#5]
Typing "exit" prints "Ran into a problem with that command: 'NoneType' object has no attribute 'name'" and doesnt exit, in latest update. A new issue, not part of previous version.

**Comment by OwenFeik** [comment]
Fixed in [this commit](https://github.com/OwenFeik/spells/commit/edf47f6493fab9375603853adaa78dea9852b5b6). Issue was that the program attempted to cache a character even if there was no current character.
